version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - cafe-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "3010:3000"
    environment:
      - ORDER_SERVICE_URL=http://order-service:3001
      - MENU_SERVICE_URL=http://menu-service:3001
      - PAYMENT_SERVICE_URL=http://payment-service:3001
      - INVENTORY_SERVICE_URL=http://inventory-service:3001
      - CUSTOMER_SERVICE_URL=http://customer-service:3001
    depends_on:
      - order-service
      - menu-service
      - payment-service
      - inventory-service
      - customer-service
    networks:
      - cafe-network

  order-service:
    build: ./order-services
    ports:
      - "3011:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/order-db
      - MENU_SERVICE_URL=http://menu-service:3001
      - PAYMENT_SERVICE_URL=http://payment-service:3001
    depends_on:
      - mongodb
    networks:
      - cafe-network

  menu-service:
    build: ./menu-services
    ports:
      - "3012:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/menu-db
    depends_on:
      - mongodb
    networks:
      - cafe-network

  payment-service:
    build: ./payment-services
    ports:
      - "3013:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/payment-db
    depends_on:
      - mongodb
    networks:
      - cafe-network

  inventory-service:
    build: ./inventory-services
    ports:
      - "3014:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/inventory-db
    depends_on:
      - mongodb
    networks:
      - cafe-network

  customer-service:
    build: ./customer-services
    ports:
      - "3015:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/customer-db
    depends_on:
      - mongodb
    networks:
      - cafe-network

networks:
  cafe-network:
    driver: bridge

volumes:
  mongodb_data:
